### ISSUE TITLE
path_upload_map service does not save maps in the cloud

### ISSUE THREAD

**Issue by dudekw** [rapp-project/rapp-api#52]
Hi @alexge233, @klpanagi !
I tied to run the path_planner [example](https://github.com/rapp-project/rapp-api/blob/cpp-wut/cpp/examples/path_planner.cpp) and it failed. We've tested it with our cloud also. Python API call works well. 

The map files are not being saved in the cloud.

Client log:
```
png: /home/wojciech/rapp/rapp-platform/rapp_path_planning/rapp_map_server/maps/empty.png
yaml: /home/wojciech/rapp/rapp-platform/rapp_path_planning/rapp_map_server/maps/empty.yaml
m_name: my_map
upload status: 
 

pose_goal: 0.2 0.2 0 0 0 0 1 
asio error: End of file
 ```
Cloud log:
```
No map image file received
```

**Comment by alexge233** [comment]
The `asio error: End of file` implies that the server hang up the connection abruptly.
I don't know why the server responds with no image file received.
I've checked the code and commited/pushed again, so make sure you pull first.
Can you `pull` then `make clean` and `make` from start?

The following lines which I've added in `includes/cloud/asio/asio_http/asio_http.cpp`

```cpp
27 std::cout << asio_handler::make_header(info, head_preamble_, content_length)
28                << post_;
```
should print out both header and post data to check if something is malformed.

TBH the platform errors are too generic, e.g., if a POST is malformed it should say so instead of the cryptic "no map image received".

**Comment by dudekw** [comment]
Thank you!
